# ---------- Build stage ----------
FROM node:20-alpine AS build

WORKDIR /client

COPY package*.json ./
RUN npm ci


COPY .env.local .   
COPY . .


RUN npm run build

FROM nginx:alpine



COPY --from=build /client/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
